language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.5
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "F1Nz5ryvEzLmlK+1dj6Wcv7BTHI1wpGRcb4YnLgjz5/gF4faSJpzkn+nBRim1UCrAJHTIsXYjkh0qdtX3TY47obAt1uMdiCx/RAN979SZh4YXnkA87Hl8MK9eeR6ZliHGmva/hQhg2MSWyP03hfJh/ddM5QCLb48u3VIuk0uRsE+p+CBwngbDA79znP2EIoN5lB6MNou1NEBcklDFEdMit3jbk/vAlZUn+4wS/tdHIBZC+hE42lSPacl/zRKTaxhqm7DpTI4yuL2AVhx87CKfsAUeJ50+8DxaI1yhpdeqdsnr2slcPqKvXdBG2+DOM43vaA1NHM5SqP28NvH8s9PB8EePuvOCxLsoDvlc847PgZBzVnV1uZY9tHP8JtVa4NG+KanO59lerafM9t9QTNn22iz0QnQ8GuiPsVRCObdjKmVciFuXTHSDk1RMWIvZ9GU8F8U/vVDYFOzV+ZX2H3sruuSSMyuhUWNlRGracmLE0TpCP05FVAd//kBbk0c1mvIfU7z+GjcQFu23eXFqV2yw4vQ5GqIvga2QKTp8I7Sxy60c1IN59b7DVz7XEVttO/49id5LK26WKXrMPLQcA2YtAXd0EzEAn58GUUDtfqaiGCNYukBgXu8+U0AN3beyovpo9fIkE9Ei2jalsJBePqgEMr+4sCPFez7BEjcX/itxn4="
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
